version: "3.7"

services:
  spark-worker:
    image: mhatreabhay/spark-worker
    container_name: spark-worker
    hostname: spark-worker
    network_mode: host
    ports:
      - "8081:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker"
